<h1><center>Assignment</center></h1>

### Consider the below code to answer further questions:

In [1]:
import numpy as np
list_ = [1, 2, 3, 4, 5]
array_list = np.array(object = list_)

### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [2]:
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


### Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [3]:
for i in list_:
    print(type(i))
for i in array_list:
    print(type(i))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


### Q3. Considering the following changes in the variable, array_list:

In [4]:
array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types of each and every element present in both the variables, list_ and array_list.

In [5]:
for i in list_:
    print(type(i))
for i in array_list:
    print(type(i))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


### Consider the below code to answer further questions:

In [6]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
num_array

array([[1, 2, 3],
       [4, 5, 6]])

Q4. Write a code to find the following characteristics of variable, num_array:
- shape
- size

In [7]:
print(num_array.shape)
print(num_array.size)

(2, 3)
6


### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [8]:
zeros_arr = np.zeros((3, 3))
zeros_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [9]:
identity_matrix = np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
